/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface GameTrexRunner {
    }
    interface MapAssessment {
    }
}
export interface GameTrexRunnerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGameTrexRunnerElement;
}
export interface MapAssessmentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMapAssessmentElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGameTrexRunnerElementEventMap {
        "gameStart": any;
        "gameScore": any;
    }
    interface HTMLGameTrexRunnerElement extends Components.GameTrexRunner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGameTrexRunnerElementEventMap>(type: K, listener: (this: HTMLGameTrexRunnerElement, ev: GameTrexRunnerCustomEvent<HTMLGameTrexRunnerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGameTrexRunnerElementEventMap>(type: K, listener: (this: HTMLGameTrexRunnerElement, ev: GameTrexRunnerCustomEvent<HTMLGameTrexRunnerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGameTrexRunnerElement: {
        prototype: HTMLGameTrexRunnerElement;
        new (): HTMLGameTrexRunnerElement;
    };
    interface HTMLMapAssessmentElementEventMap {
        "location": any;
    }
    interface HTMLMapAssessmentElement extends Components.MapAssessment, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMapAssessmentElementEventMap>(type: K, listener: (this: HTMLMapAssessmentElement, ev: MapAssessmentCustomEvent<HTMLMapAssessmentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMapAssessmentElementEventMap>(type: K, listener: (this: HTMLMapAssessmentElement, ev: MapAssessmentCustomEvent<HTMLMapAssessmentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMapAssessmentElement: {
        prototype: HTMLMapAssessmentElement;
        new (): HTMLMapAssessmentElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "game-trex-runner": HTMLGameTrexRunnerElement;
        "map-assessment": HTMLMapAssessmentElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface GameTrexRunner {
        "onGameScore"?: (event: GameTrexRunnerCustomEvent<any>) => void;
        "onGameStart"?: (event: GameTrexRunnerCustomEvent<any>) => void;
    }
    interface MapAssessment {
        "onLocation"?: (event: MapAssessmentCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "game-trex-runner": GameTrexRunner;
        "map-assessment": MapAssessment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "game-trex-runner": LocalJSX.GameTrexRunner & JSXBase.HTMLAttributes<HTMLGameTrexRunnerElement>;
            "map-assessment": LocalJSX.MapAssessment & JSXBase.HTMLAttributes<HTMLMapAssessmentElement>;
        }
    }
}
